create_user:
    path: /user/create
    controller: App\Controller\WriteController::createUser
    methods: POST

create_meeting:
    path: /meeting/create
    controller: App\Controller\WriteController::createMeeting
    methods: POST

invite_user_to_meeting:
    path: /meeting/invite
    controller: App\Controller\WriteController::inviteUserToMeeting
    methods: POST

delete_user_from_meeting:
    path: /user/deleteFromMeeting
    controller: App\Controller\WriteController::deleteUserFromMeeting
    methods: POST

delete_meeting:
    path: /meeting/delete
    controller: App\Controller\WriteController::deleteMeeting
    methods: POST

delete_user:
    path: /user/delete
    controller: App\Controller\WriteController::deleteUser
    methods: POST

get_all_users:
    path: /get/allUsers
    controller: App\Controller\ReadController::getAllUsers
    methods: GET

get_meetings_with_participant:
    path: /get/meetingsWithParticipant
    controller: App\Controller\ReadController::getMeetingsWithParticipant
    methods: GET

get_meetings_with_organizer:
    path: /get/meetingsWithOrganizer
    controller: App\Controller\ReadController::getMeetingsWithOrganizer
    methods: GET

get_participants_with_organizer:
    path: /get/participantsWithOrganizer
    controller: App\Controller\ReadController::getParticipantsWithOrganizer
    methods: GET


