#index:
#    path: /
#    controller: App\Controller\DefaultController::index


create_user:
    path: /user/create
    controller: App\Controller\WriteController::createUser
    methods: POST

create_meeting:
    path: /meeting/create
    controller: App\Controller\WriteController::createMeeting
    methods: POST
