create_user:
    path: /user/create
    controller: App\Controller\WriteController::createUser
    methods: POST

create_meeting:
    path: /meeting/create
    controller: App\Controller\WriteController::createMeeting
    methods: POST

invite_user_to_meeting:
    path: /meeting/participant/invite
    controller: App\Controller\WriteController::inviteMeetingParticipant
    methods: POST

delete_user_from_meeting:
    path: /meeting/participant/delete
    controller: App\Controller\WriteController::deleteMeetingParticipant
    methods: POST

delete_meeting:
    path: /meeting/delete
    controller: App\Controller\WriteController::deleteMeeting
    methods: POST

delete_user:
    path: /user/delete
    controller: App\Controller\WriteController::deleteUser
    methods: POST

get_all_users:
    path: /get/users
    controller: App\Controller\ReadController::getAllUsers
    methods: GET

get_meetings_with_participant:
    path: /get/participant/meetings
    controller: App\Controller\ReadController::getMeetingsWithParticipant
    methods: GET

get_meetings_with_organizer:
    path: /get/organizer/meetings
    controller: App\Controller\ReadController::getMeetingsWithOrganizer
    methods: GET

get_participants_with_organizer:
    path: /get/participants/as/organizer
    controller: App\Controller\ReadController::getParticipantsWithOrganizer
    methods: GET


